services:
  postgres:
    image: postgres:18
    container_name: igloo_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-igloo_db}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-12345678}
    ports:
      - ${POSTGRES_PORT:-5435}:5432
    volumes:
      - postgres_data:/var/lib/postgresql

  postgres-test:
    image: postgres:18
    container_name: igloo_postgres_test
    environment:
      POSTGRES_DB: igloo_test_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
    ports:
      - 5436:5432
    volumes:
      - postgres_test_data:/var/lib/postgresql

  pgadmin:
    image: dpage/pgadmin4
    container_name: igloo_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: 12345678
    ports:
      - "8080:80"
    depends_on:
      - postgres
      - postgres-test
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  minio:
    image: minio/minio:RELEASE.2025-02-03T21-03-04Z-cpuv1
    container_name: igloo_minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    ports:
      - "9000:9000" # API S3
      - "9001:9001" # Console
    volumes:
      - minio_data:/data

volumes:
  postgres_data:
  postgres_test_data:
  pgadmin_data:
  minio_data:
